---
resources:

- name: scdf-demo
  type: git
  source:
    uri: https://github.com/cpage-pivotal/scdf-demo
    branch: master
    
- name: scdf-server
  type: s3
  source:
    access_key_id: AKIAIVQSSOTGEE23A4HQ
    secret_access_key: 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
    bucket: scdf-apps
    regexp: spring-cloud-dataflow-server-cloudfoundry-(.*).RELEASE.jar

#- name: nlp-proxy-processor
#  type: s3
#  source:
#    bucket: scdf-apps
#    regexp: nlp-proxy-processor-(.*).jar
#
#- name: redis-sink
#  type: s3
#  source:
#    bucket: scdf-apps
#    regexp: redis-sink-(.*).jar

- name: pcf-env
  type: cf
  source:
    api: {{CF_API}}
    username: {{CF_USER}}
    password: {{CF_PASSWORD}}
    organization: {{CF_ORG}}
    space: {{CF_SPACE}}
    skip_cert_check: true


cf-params: &cf-params
  CF_API_URL: {{CF_API}}
  CF_SKIP_SSL: true
  CF_USERNAME: {{CF_USER}}
  CF_PASSWORD: {{CF_PASSWORD}}
  CF_ORG: {{CF-ORG}}
  CF_SPACE: {{CF_SPACE}}

jobs:

- name: prepare-cf
  plan:
  - get: scdf-demo
  - task: prepare-cf-task
    file: pipeline/ci/prepare-cf.yml
    params:
      <<: *cf-params
      CF_DB_SERVICE_NAME: {{DB_SERVICE_NAME}}
      CF_DB_SERVICE_PLAN: {{DB_SERVICE_PLAN}}
      CF_RABBIT_SERVICE_NAME: {{RABBIT_SERVICE_NAME}}
      CF_RABBIT_SERVICE_PLAN: {{RABBIT_SERVICE_PLAN}}
      CF_REDIS_SERVICE_NAME: {{REDIS_SERVICE_NAME}}
      CF_REDIS_SERVICE_PLAN: {{REDIS_SERVICE_PLAN}}

- name: deploy-scdf
  plan:
  - get: scdf-server
  - get: scdf-demo
  - passed: prepare-cf

  - put: pcf-env
    params:
      manifest: scdf-demo/ci/manifest.yml
      environment_variables:
        SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_URL: {{CF_API}}
        SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_ORG: {{CF_ORG}}
        SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SPACE: {{CF_SPACE}}
        SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_DOMAIN: {{CF_DOMAIN}} 
        SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_USERNAME: {{CF_USER}}
        SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_PASSWORD: {{CF_PASSWORD}}
        SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SKIP_SSL_VALIDATION: {{CF_SKIP_SSL}}
        SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_BUILDPACK: {{CF_BUILDPACK}}
        SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_MEMORY: "1024"
        SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_SERVICES: scdf-redis,scdf-rabbit
        SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_APP_NAME_PREFIX: {{CF_APP_NAME_PREFIX}}
        SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_ENABLE_RANDOM_APP_NAME_PREFIX: "false"
        MAVEN_REMOTE_REPOSITORIES_REPO1_URL: https://repo.spring.io/libs-snapshot

