---
resources:

- name: scdf-demo
  type: git
  source:
    uri: https://github.com/cpage-pivotal/scdf-demo
    branch: master
    
- name: scdf-server
  type: s3
  source:
    access_key_id: {{AWS_ACCESS_KEY}}
    secret_access_key: {{AWS_SECRET_KEY}}
    bucket: scdf-apps
    regexp: spring-cloud-dataflow-server-cloudfoundry-(.*).RELEASE.jar

- name: pcf-env
  type: cf
  source:
    api: {{CF_API}}
    username: {{CF_USER}}
    password: {{CF_PASSWORD}}
    organization: {{CF_ORG}}
    space: {{CF_SPACE}}
    skip_cert_check: true

cf-params: &cf-params
  CF_API: {{CF_API}}
  CF_SKIP_SSL: true
  CF_USER: {{CF_USER}}
  CF_PASSWORD: {{CF_PASSWORD}}
  CF_ORG: {{CF_ORG}}
  CF_SPACE: {{CF_SPACE}}

jobs:

- name: deploy-scdf
  plan:
  - get: scdf-demo
  - get: scdf-server
  - task: prepare-cf
    file: scdf-demo/ci/prepare-cf.yml
    params:
      <<: *cf-params
      CF_DB_SERVICE_NAME: {{DB_SERVICE_NAME}}
      CF_DB_SERVICE_PLAN: {{DB_SERVICE_PLAN}}
      CF_RABBIT_SERVICE_NAME: {{RABBIT_SERVICE_NAME}}
      CF_RABBIT_SERVICE_PLAN: {{RABBIT_SERVICE_PLAN}}
      CF_REDIS_SERVICE_NAME: {{REDIS_SERVICE_NAME}}
      CF_REDIS_SERVICE_PLAN: {{REDIS_SERVICE_PLAN}}
  - put: pcf-env
    params:
      manifest: scdf-demo/ci/dataflow-server-manifest.yml
      environment_variables:
        SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_URL: {{CF_API}}
        SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_ORG: {{CF_ORG}}
        SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SPACE: {{CF_SPACE}}
        SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_DOMAIN: {{CF_DOMAIN}}
        SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_USERNAME: {{CF_USER}}
        SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_PASSWORD: {{CF_PASSWORD}}
        SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SKIP_SSL_VALIDATION: {{CF_SKIP_SSL}}
        SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_BUILDPACK: {{CF_BUILDPACK}}
        SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_MEMORY: "1024"
        SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_SERVICES: scdf-redis,scdf-rabbit
        SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_APP_NAME_PREFIX: {{CF_APP_NAME_PREFIX}}
        SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_ENABLE_RANDOM_APP_NAME_PREFIX: "false"
        MAVEN_REMOTE_REPOSITORIES_REPO1_URL: https://repo.spring.io/libs-snapshot

- name: deploy-bubble
  plan:
  - get: scdf-demo
  - task: build-bubble
    file: scdf-demo/ci/build-bubble.yml
  - put: pcf-env
    params:
      manifest: scdf-demo/ci/bubble-manifest.yml

- name: register-apps
  plan:
  - get: scdf-demo
  - task: run-register-apps
    file: scdf-demo/ci/run-register-apps.yml
